language: python
sudo: false
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=4.3.x
    - python: "2.7"
      env: PLONE_VERSION=5.0.x
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.6"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
      dist: xenial
      sudo: true
cache:
  pip: true
  directories:
  - eggs
  - downloads
before_install:
# install chrome webdriver
  - mkdir webdriver;
    wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip;
    unzip chromedriver_linux64.zip -d webdriver;
    export PATH=$PATH:$(pwd)/webdriver;
  - pip install zc.buildout
  - cp test-$PLONE_VERSION.cfg buildout.cfg
install:
  - buildout -N -t 3 annotate
  - buildout -N -t 3
script:
# Run code-analysis, except on Python 3.6, which mysteriously fails to find zc.buildout.
  - python --version 2> /dev/stdout | grep 3.6 || bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls
  - coveralls
notifications:
  irc: irc.freenode.org#plone-testing
